// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFfWftwavDlX2sIIsetL3IJ75mx-xBJO8',
    appId: '1:859657594757:android:204df2bbe1b364ecc686ec',
    messagingSenderId: '859657594757',
    projectId: 'fir-flutterapp-87fcd',
    databaseURL: 'https://fir-flutterapp-87fcd-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutterapp-87fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvdH3A9aGRy6qLq-2DkQ0CV95WgruQJAk',
    appId: '1:859657594757:ios:e42866916d91cd00c686ec',
    messagingSenderId: '859657594757',
    projectId: 'fir-flutterapp-87fcd',
    databaseURL: 'https://fir-flutterapp-87fcd-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutterapp-87fcd.appspot.com',
    iosClientId: '859657594757-o3gefhm7g98jqt7rgdhdimkkcg8tg32l.apps.googleusercontent.com',
    iosBundleId: 'com.example.cognitivegmae',
  );
}
