/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class MyFlutterIcon {
  MyFlutterIcon._();

  static const _kFontFam = 'MyFlutterIcon';
  static const Null _kFontPkg = null;

  static const IconData goat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rabbit = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crocodile = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData elephant = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bird = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horse = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snake = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_upward = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
